
-- Create Table
CREATE TABLE Country
(
	CountryID TINYINT PRIMARY KEY,
	CountryName VARCHAR(50) NULL
)

CREATE TABLE Calendar
(
	DateID VARCHAR(50) NOT NULL PRIMARY KEY,
	Date DATE NOT NULL,
	Day TINYINT NOT NULL,
	Month TINYINT NOT NULL,
	Year TINYINT NOT NULL
)

CREATE TABLE Membership
(
	MembershipID TINYINT PRIMARY KEY,
	Membership VARCHAR(50) NOT NULL,
	Cost MONEY NOT NULL
)


CREATE TABLE UserInfo
(
	UserID VARCHAR(50) NOT NULL PRIMARY KEY,
	UserName VARCHAR(50) NOT NULL,
	RegisteredDateID VARCHAR(50) FOREIGN KEY REFERENCES Calendar(DateID),
	RegisterDate DATE NOT NULL,
	CountryName VARCHAR(50) NULL,
	MembershipID TINYINT FOREIGN KEY REFERENCES Membership(MembershipID),
	Email VARCHAR(50) NULL,
	Age TINYINT NULL,
	Gender VARCHAR(50) NULL
);

CREATE TABLE Transactions
(
	SessionID VARCHAR(50) NOT NULL PRIMARY KEY,
	UserID VARCHAR(50) FOREIGN KEY REFERENCES UserInfo(UserID),
	CountryID TINYINT FOREIGN KEY REFERENCES Country(CountryID),
	StartDateID VARCHAR(50) NOT NULL,
	StartDate DATE NOT NULL,
	StartTimestamp INT NOT NULL,
	EndTimestamp INT NOT NULL,
	CashSpend MONEY NOT NULL,
	CountImpression TINYINT NULL,
	eCPM MONEY NULL,
	OS VARCHAR(50) NULL,
	OsVersion VARCHAR(50) NULL
)
-- Create Agent Job / Schedule

-- Create Stored Procedure
