CREATE ROLE TRAINER_ROLE;
USER ROLE ACCCOUNTADMIN;

GRANT ALL ON WAREHOUSE GAMING_WH TO TRAINER_ROLE;
GRANT ALL ON DATABASE GAMINGGROUP6 TO ROLE TRAINER_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE GAMINGGROUP6 TO ROLE TRAINER_ROLE;
GRANT ALL ON TABLE GAMINGGROUP6.PUBLIC.DIM_CALENDAR TO ROLE TRAINER_ROLE;
GRANT ALL ON TABLE GAMINGGROUP6.PUBLIC.DIM_COUNTRY TO ROLE TRAINER_ROLE;
GRANT ALL ON TABLE GAMINGGROUP6.PUBLIC.DIM_MEMBERSHIP TO ROLE TRAINER_ROLE;
GRANT ALL ON TABLE GAMINGGROUP6.PUBLIC.DIM_USER TO ROLE TRAINER_ROLE;
GRANT ALL ON TABLE GAMINGGROUP6.PUBLIC.FACT_TRANSACTIONS TO ROLE TRAINER_ROLE;

CREATE USER LongBV1
PASSWORD = 'Trainers123'
DEFAULT_ROLE = 'TRAINER_ROLE'
DEFAULT_WAREHOUSE = 'GAMING_WH';
GRANT ROLE TRAINER_ROLE TO USER LongBV1;

CREATE USER MaiNQ2
PASSWORD = 'Trainers123'
DEFAULT_ROLE = 'TRAINER_ROLE'
DEFAULT_WAREHOUSE = 'GAMING_WH';
GRANT ROLE TRAINER_ROLE TO USER MaiNQ2;
