put file://c:\Users\LinhTK9\gaming-project\resources\data-snowflake\*.csv @project_stage/upload;
COPY INTO USERINFO FROM @project_stage/upload/UserInfoSnowflake.csv.gz;
COPY INTO TRANSACTIONS FROM @project_stage/upload/TransactionsSnowflake.csv.gz;
COPY INTO MEMBERSHIP FROM @project_stage/upload/MembershipSnowflake.csv.gz;
COPY INTO COUNTRY FROM @project_stage/upload/CountrySnowflake.csv.gz;
COPY INTO CALENDAR FROM @project_stage/upload/CalendarSnowflake.csv.gz;

INSERT OVERWRITE INTO DIM_CALENDAR(DATEID, DATE, DAY, MONTH, YEAR)
SELECT DISTINCT DATEID, DATE, DAY, MONTH, YEAR FROM CALENDAR;

INSERT OVERWRITE INTO DIM_MEMBERSHIP(MEMBERSHIPID, MEMBERSHIP, COST)
SELECT DISTINCT MEMBERSHIPID, MEMBERSHIP, COST FROM MEMBERSHIP;

INSERT OVERWRITE INTO DIM_COUNTRY(COUNTRYID, COUNTRYNAME)
SELECT DISTINCT COUNTRYID,COUNTRYNAME FROM COUNTRY;

INSERT OVERWRITE INTO DIM_USER(USERID, USERNAME, EMAIL, AGE, GENDER)
SELECT DISTINCT USERID, USERNAME, EMAIL, AGE, GENDER FROM USERINFO;

INSERT INTO FACT_TRANSACTIONS(USERID, COUNTRYID, STARTDATEID, STARTDATE, REGISTEREDDATEID,
                              REGISTERDATE, PLAYINGDURATION, MEMBERSHIPID, MEMBERSHIPCOST, CASHSPEND,
                              COUNTIMPRESSION, UNITCPM, ERNEDFROMAD, TOTALINCOME)
SELECT * FROM V_FACT;

TRUNCATE TABLE MEMBERSHIP;
TRUNCATE TABLE COUNTRY;
TRUNCATE TABLE CALENDAR;
TRUNCATE TABLE TRANSACTIONS;

REMOVE @project_stage/upload/UserInfoSnowflake.csv.gz;
REMOVE @project_stage/upload/TransactionsSnowflake.csv.gz;






